[Variables]
; Base
; Search
f_AddSearchInputToRecent=[!WriteKeyValue Variables Recent5 "#Recent4#" "#@#includes\settings\search-recent.inc"][!WriteKeyValue Variables Recent4 "#Recent3#" "#@#includes\settings\search-recent.inc"][!WriteKeyValue Variables Recent3 "#Recent2#" "#@#includes\settings\search-recent.inc"][!WriteKeyValue Variables Recent2 "#Recent1#" "#@#includes\settings\search-recent.inc"][!WriteKeyValue Variables Recent1 "[SearchInput]" "#@#includes\settings\search-recent.inc"]